apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-remote-mar17-1
  janus-idp.io/tekton: codegen-remote-mar17-1
  backstage.io/kubernetes-id: codegen-remote-mar17-1
  backstage.io/kubernetes-namespace: mar17-1
  app.kubernetes.io/part-of: codegen-remote-mar17-1
resources:
- application-dev.yaml
- application-tekton.yaml