apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: codegen-remote-mar17-1-gitops-repository
spec:
  url: https://github.com/redhat-appstudio-mjf/codegen-remote-mar17-1-gitops
